source /home/vancir/Documents/code/SSMS/sql/root.sql
source /home/vancir/Documents/code/SSMS/sql/admin.sql
source /home/vancir/Documents/code/SSMS/sql/sp_createUser.sql
source /home/vancir/Documents/code/SSMS/sql/sp_validateLogin.sql
source /home/vancir/Documents/code/SSMS/sql/admin_insert_user_info.sql
source /home/vancir/Documents/code/SSMS/sql/admin_revoke_user_access.sql
source /home/vancir/Documents/code/SSMS/sql/teacher_insert_TC.sql
source /home/vancir/Documents/code/SSMS/sql/student_select_student_info.sql
source /home/vancir/Documents/code/SSMS/sql/admin_select_SC_info.sql
source /home/vancir/Documents/code/SSMS/sql/admin_select_student_info.sql    
source /home/vancir/Documents/code/SSMS/sql/admin_select_TC_info.sql
source /home/vancir/Documents/code/SSMS/sql/teacher_select_SC_info.sql
source /home/vancir/Documents/code/SSMS/sql/admin_select_teacher_info.sql
source /home/vancir/Documents/code/SSMS/sql/teacher_select_student_info.sql
source /home/vancir/Documents/code/SSMS/sql/admin_select_user_info.sql 
source /home/vancir/Documents/code/SSMS/sql/teacher_select_teacher_info.sql
source /home/vancir/Documents/code/SSMS/sql/student_select_course_info.sql
source /home/vancir/Documents/code/SSMS/sql/admin_select_course_info.sql
source /home/vancir/Documents/code/SSMS/sql/admin_delete_course_info.sql
source /home/vancir/Documents/code/SSMS/sql/admin_delete_student_info.sql
source /home/vancir/Documents/code/SSMS/sql/admin_select_major_info.sql
source /home/vancir/Documents/code/SSMS/sql/teacher_select_TC.sql
source /home/vancir/Documents/code/SSMS/sql/admin_delete_teacher_info.sql
source /home/vancir/Documents/code/SSMS/sql/admin_update_course_info.sql
source /home/vancir/Documents/code/SSMS/sql/student_insert_SC.sql
source /home/vancir/Documents/code/SSMS/sql/teacher_update_scScore.sql
source /home/vancir/Documents/code/SSMS/sql/admin_GRANT_user_access.sql
source /home/vancir/Documents/code/SSMS/sql/admin_update_student_info.sql
source /home/vancir/Documents/code/SSMS/sql/student_select_ctermScore.sql
source /home/vancir/Documents/code/SSMS/sql/admin_insert_course_info.sql
source /home/vancir/Documents/code/SSMS/sql/admin_update_teacher_info.sql
source /home/vancir/Documents/code/SSMS/sql/student_select_SC.sql
source /home/vancir/Documents/code/SSMS/sql/admin_insert_major_info.sql


source /home/vancir/Documents/code/SSMS/sql/data.sql
